name: jupyter-actions
channels:
    - conda-forge
dependencies:
  - jupyter=1.0
  - nbformat
  - nbconvert
  - numpy
  - seaborn
  - xls
  - requests=2.24.0
  - pytest
  - vtk
  - pyevtk
  - xlwt
  - swig